# Generated by Django 3.0.1 on 2020-02-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_minion', '0002_auto_20200208_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
