# Generated by Django 3.0.1 on 2020-02-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_minion', '0003_auto_20200208_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='auth_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
