# Generated by Django 3.0.1 on 2020-03-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_minion', '0008_spotifytasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifyuser',
            old_name='dw_updated_at',
            new_name='dw_monthly_updated_at',
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='dw_yearly_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
