# Generated by Django 3.0.1 on 2020-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_minion', '0009_auto_20200330_1659'),
    ]

    operations = [

    ]
