# Generated by Django 3.0.1 on 2020-04-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_minion', '0010_auto_20200404_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyTasks',
        ),
    ]
