# Generated by Django 3.0.1 on 2020-04-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_minion', '0011_delete_spotifytasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=250)),
                ('task_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(editable=False)),
                ('next_run_time', models.DateTimeField()),
            ],
        ),
    ]
