# Generated by Django 3.0.1 on 2020-04-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_minion', '0012_spotifytasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='spotifytasks',
            name='next_run_time',
            field=models.DateTimeField(null=True),
        ),
    ]
